# Generated by Django 3.2.6 on 2025-09-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ('producto', '0001_initial'),
    ('users', '0001_initial'),
]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50, default='pendiente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='producto.producto')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.users')),
            ],
        ),
    ]
