# Generated by Django 3.2.6 on 2025-09-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('bodega', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
