# Generated by Django 3.2.6 on 2025-09-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bodega',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
