# Generated by Django 3.2.6 on 2025-09-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.FloatField(blank=True, default=None, null=True)),
                ('bodega', models.IntegerField(blank=True, default=None, null=True)),
                ('estante', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
