# Generated by Django 3.2.6 on 2025-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(unique=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
            ],
        ),
    ]
